#配置tomcat端口
server.port: 8088
#springboot整合mybatis
spring:
    datasource:
       name: mySqlDb
       type: com.alibaba.druid.pool.DruidDataSource
       url: jdbc:mysql://127.0.0.1:3306/springboot?characterEncoding=utf8
       username: root
       password: 111
       driver-class-name: com.mysql.jdbc.Driver
       minIdle: 10
       maxActive: 300
       maxWait: 60000
       initialSize: 100
       timeBetweenEvictionRunsMillis: 30000
       minEvictableIdleTimeMillis: 30000
       maxEvictableIdleTimeMillis: 60000
       validationQuery: SELECT 'x'
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
       poolPreparedStatements: true
       maxPoolPreparedStatementPerConnectionSize: 20
       filters: stat,wall,log4j
       connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
       keepAlive: true
       removeAbandoned: true
       removeAbandonedTimeout: 60
       logAbandoned: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.hzjy.demo.pojo
